- name: qdrouterd-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: ansible.kubernetes-modules
      install_python_requirements: no

    - openstack-ansible-plugins

    - role: k8s-qdrouterd
      playbook_debug: false
