- name: Deprovision mariadb
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: ansible.kubernetes-modules
      install_python_requirements: no

    - role: k8s-mariadb
      action: deprovision
      playbook_debug: false
