- name: keystone-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: openstack-ansible-plugins
  - role: provision-keystone-apb
    playbook_debug: false
